version: '3.8'

services:
  # TimescaleDB container
  # timescaledb:
  #   image: timescale/timescaledb:latest-pg14
  #   container_name: timescaledb
  #   volumes:
  #     - timescaledb_data:/var/lib/postgresql/data
  #   environment:
  #     POSTGRES_DB: 'postgres'
  #     POSTGRES_USER: 'postgres'
  #     POSTGRES_PASSWORD: 'password'
  #   ports:
  #     - "5432:5432"

  timescaledb:
    build:
      context: .
      dockerfile: Dockerfile.timescaledb
    container_name: timescale
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres
    ports:
      - '5432:5432'
    volumes:
    # Mount the init_timescaledb.sql file to the Docker container's /docker-entrypoint-initdb.d/ directory
    - ./init_timescaledb.sql:/docker-entrypoint-initdb.d/init_timescaledb.sql

  # Node.js backend and Angular frontend containers
  web_app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: data_metrics_app
    ports:
      - "3000:3000"
    depends_on:
      - timescaledb
    environment:
      - DATABASE_URL=postgres://postgres:password@timescaledb:5432/postgres

volumes:
  timescaledb_data:
    driver: local
