{
 "title": "Job wise - Completed Production",
 "time": { "from": "now-7d", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "job",
    "label": "job",
    "query": "select distinct(trim(job)) from job_details order by trim(job)"
   }
  ]
 },
 "panels": [
  {
   "title": "Prod Quantity of ${job}",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 13, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "\nSELECT sum(target_qty) target_qty, sum(actual_qty) actual_qty_produced\nFROM  job_details\nWHERE '['$__timeFrom()', '$__timeTo()']'::tsrange @> shift\n  and job in ('${job}')\n--group by machine"
    }
   ]
  },
  {
   "title": "Efficiency of ${job}",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 11, "x": 13, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "rawSql": "\nSELECT sum(actual_qty)/sum(target_qty)::float * 100 as efficiency\nFROM  job_details\nWHERE '['$__timeFrom()', '$__timeTo()']'::tsrange @> shift\n  and job = '$job'\n--group by job"
    }
   ]
  },
  {
   "title": "Actual Strokes vs Actual Quantity of ${job}",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 13, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select actual_qty actual_qty_produced, total_strokes strokes_taken\nFROM (\nselect job, count(eventtime) total_strokes\nfrom job_details jd left join sensor s on jd.machine = s.machine and eventtime <@ shift\nwhere '['$__timeFrom()', '$__timeTo()']'::tsrange @> shift \ngroup by job\n)s join (\n  select job, sum(actual_qty) actual_qty \n  from job_details \n  WHERE '['$__timeFrom()', '$__timeTo()']'::tsrange @> shift \n  GROUP BY job\n) jd on s.job = jd.job\nwhere jd.job = '${job}'"
    }
   ]
  },
  {
   "title": "Idle strokes % of ${job}",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 11, "x": 13, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "rawSql": "select (total_strokes-actual_qty)/actual_qty::float * 100 efficiency\nFROM (\nselect job, count(eventtime) total_strokes\nfrom job_details jd left join sensor s on jd.machine = s.machine and eventtime <@ shift\nwhere '['$__timeFrom()', '$__timeTo()']'::tsrange @> shift \ngroup by job\n)s join (\n  select job, sum(actual_qty) actual_qty \n  from job_details \n  WHERE '['$__timeFrom()', '$__timeTo()']'::tsrange @> shift \n  GROUP BY job\n) jd on s.job = jd.job\nwhere jd.job = '${job}'"
    }
   ]
  }
 ]
}