{
 "title": "Job wise - Completed Production",
 "time": { "from": "now-7d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "job",
    "label": "job",
    "query": "select distinct(trim(job_name)) from job_details order by trim(job_name)"
   }
  ]
 },
 "panels": [
  {
   "title": "Prod Quantity of ${job}",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 13, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "\n--SELECT TO_TIMESTAMP($__unixEpochFrom()), $__timeFrom()\n--select tstzrange( to_timestamp($__unixEpochFrom()) AT time zone 'Asia/Kolkata',to_timestamp($__unixEpochTo()) AT time zone 'Asia/Kolkata' ), $__timeFrom()\nSELECT sum(target_qty) target_qty, sum(actual_qty) actual_qty_produced\nFROM  job_details\nWHERE tstzrange( to_timestamp($__unixEpochFrom()) AT time zone 'Asia/Kolkata',to_timestamp($__unixEpochTo()) AT time zone 'Asia/Kolkata' ) @> shift\n  and job_name in ('${job}')\n--group by machine"
    }
   ]
  },
  {
   "title": "Efficiency of ${job}",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 11, "x": 13, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "rawSql": "\nSELECT sum(actual_qty)/sum(target_qty)::float * 100 as efficiency\nFROM  job_details\nWHERE tstzrange( to_timestamp($__unixEpochFrom()) AT time zone 'Asia/Kolkata',to_timestamp($__unixEpochTo()) AT time zone 'Asia/Kolkata' ) @> shift\n  and job_name in ('${job}')\n--group by job\n"
    }
   ]
  },
  {
   "title": "Actual Strokes vs Actual Quantity of ${job}",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 13, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select actual_qty actual_qty_produced, total_strokes strokes_taken\nFROM (\nselect job_name, count(eventtime) total_strokes\nfrom job_details jd left join sensor s on jd.machine = s.machine and eventtime <@ shift\nwhere tstzrange( to_timestamp($__unixEpochFrom()) AT time zone 'Asia/Kolkata',to_timestamp($__unixEpochTo()) AT time zone 'Asia/Kolkata' ) @> shift \ngroup by job_name\n)s join (\n  select job_name, sum(actual_qty) actual_qty \n  from job_details \n  WHERE tstzrange( to_timestamp($__unixEpochFrom()) AT time zone 'Asia/Kolkata',to_timestamp($__unixEpochTo()) AT time zone 'Asia/Kolkata' ) @> shift \n  GROUP BY job_name\n) jd on s.job_name = jd.job_name\nwhere jd.job_name = '${job}'\n"
    }
   ]
  },
  {
   "title": "Idle strokes % of ${job}",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 11, "x": 13, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "rawSql": "select (total_strokes-actual_qty)/actual_qty::float * 100 efficiency\nFROM (\nselect job_name, count(eventtime) total_strokes\nfrom job_details jd left join sensor s on jd.machine = s.machine and eventtime <@ shift\nwhere tstzrange( to_timestamp($__unixEpochFrom()) AT time zone 'Asia/Kolkata',to_timestamp($__unixEpochTo()) AT time zone 'Asia/Kolkata' ) @> shift \ngroup by job_name\n)s join (\n  select job_name, sum(actual_qty) actual_qty \n  from job_details \n  WHERE tstzrange( to_timestamp($__unixEpochFrom()) AT time zone 'Asia/Kolkata',to_timestamp($__unixEpochTo()) AT time zone 'Asia/Kolkata' ) @> shift \n  GROUP BY job_name\n) jd on s.job_name = jd.job_name\nwhere jd.job_name = '${job}'"
    }
   ]
  }
 ]
}