{
 "title": "Machine wise - Completed Production",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "machine",
    "label": "machine",
    "query": "select distinct(trim(machine)) from job_details"
   }
  ]
 },
 "panels": [
  {
   "title": "Prod Quantity of ${machine}",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 13, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "\nSELECT sum(target_qty) target_qty, sum(actual_qty) actual_qty_produced\nFROM  job_details\nWHERE '['$__timeFrom()', '$__timeTo()']'::tsrange @> shift\n  and machine = '${machine}'\n--group by machine"
    }
   ]
  },
  {
   "title": "Efficiency",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 11, "x": 13, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "rawSql": "\nSELECT \ndevice, sum(actual_qty)/sum(target_qty)::float * 100 as efficiency\nFROM  job_details\nWHERE '['$__timeFrom()', '$__timeTo()']'::tsrange @> shift\n  and machine = '$machine'\ngroup by machine"
    }
   ]
  },
  {
   "title": "Actual Strokes vs Actual Quantity of ${machine}",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 13, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select actual_qty actual_qty_produced, total_strokes strokes_taken\nFROM (\n  select machine, count(eventtime) total_strokes\n  FROM sensor \n  WHERE eventtime between $__timeFrom() AND $__timeTo()\n  GROUP BY machine\n)s join (\n  select machine, sum(actual_qty) actual \n  from job_details \n  WHERE '['$__timeFrom()', '$__timeTo()']'::tsrange @> shift \n  GROUP BY machine\n) jd on s.machine = jd.machine\nwhere s.machine = '${machine}'\n"
    }
   ]
  },
  {
   "title": "Idle strokes % of ${machine}",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 11, "x": 13, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "rawSql": "select (total_strokes-actual)/actual_qty::float * 100 efficiency\nFROM (\n  select machine, count(eventtime) total_strokes\n  FROM sensor \n  WHERE eventtime between $__timeFrom() AND $__timeTo()\n  GROUP BY machine\n)s join (\n  select machine, sum(actual_qty) actual \n  from job_details \n  WHERE '['$__timeFrom()', '$__timeTo()']'::tsrange @> shift \n  GROUP BY machine\n) jd on s.machine = jd.machine\nwhere s.machine = '${machine}'\n"
    }
   ]
  }
 ]
}