{
 "title": "Machine wise - Completed Production",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "machine",
    "label": "machine",
    "query": "select distinct(trim(machine)) from job_details"
   },
   {
    "name": "job",
    "label": "job",
    "query": "select distinct(trim(job_name)) from job_details order by trim(job_name)"
   }
  ]
 },
 "panels": [
  {
   "title": "Prod Quantity of ${machine} (${job})",
   "type": "bargauge",
   "gridPos": { "h": 11, "w": 13, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "\nSELECT sum(target_qty) target_qty, sum(actual_qty) actual_qty_produced\nFROM  job_details\nWHERE '['$__timeFrom()', '$__timeTo()']'::tstzrange @> shift\n  and machine = '${machine}'\n--group by device"
    }
   ]
  },
  {
   "title": "Efficiency of ${machine} (${job})",
   "type": "gauge",
   "gridPos": { "h": 11, "w": 11, "x": 13, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT \r\nmachine, sum(actual_qty)/sum(target_qty)::float * 100 as efficiency\r\nFROM  job_details\r\nWHERE '['$__timeFrom()', '$__timeTo()']'::tstzrange @> shift\r\n  and machine = '$machine'\r\ngroup by machine\r\n"
    }
   ]
  },
  {
   "title": "Actual Strokes vs Actual Quantity of ${machine} (${job})",
   "type": "bargauge",
   "gridPos": { "h": 11, "w": 13, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select actual_qty actual_qty_produced, total_strokes strokes_taken\nFROM (\n  select machine, count(eventtime) total_strokes\n  FROM sensor \n  WHERE eventtime between $__timeFrom() AND $__timeTo()\n  GROUP BY machine\n)s join (\n  select machine, sum(actual_qty) actual_qty \n  from job_details \n  WHERE '['$__timeFrom()', '$__timeTo()']'::tstzrange @> shift \n  GROUP BY machine\n) jd on s.machine = jd.machine\nwhere s.machine = '${machine}'\n"
    }
   ]
  },
  {
   "title": "Idle strokes % of ${machine} (${job})",
   "type": "gauge",
   "gridPos": { "h": 11, "w": 11, "x": 13, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "rawSql": "select (total_strokes-actual_qty)/total_strokes::float * 100 efficiency\nFROM (\n  select machine, count(eventtime) total_strokes\n  FROM sensor \n  WHERE eventtime between $__timeFrom() AND $__timeTo()\n  GROUP BY machine\n)s join (\n  select machine, sum(actual_qty) actual_qty \n  from job_details \n  WHERE '['$__timeFrom()', '$__timeTo()']'::tstzrange @> shift \n  GROUP BY machine\n) jd on s.machine = jd.machine\nwhere s.machine = '${machine}'\n"
    }
   ]
  }
 ]
}