{
 "title": "Operator wise - Completed Production",
 "time": { "from": "now-7d", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "operator",
    "label": "operator",
    "query": "select distinct(trim(operator)) from job_details"
   }
  ]
 },
 "panels": [
  {
   "title": "Prod Quantity by ${operator}",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 13, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "\nSELECT sum(target_qty) target_qty, sum(actual_qty) actual_qty_produced\nFROM  job_details\nWHERE '['$__timeFrom()', '$__timeTo()']'::tsrange @> shift\n  and operator in ('${operator}')\n--group by machine"
    }
   ]
  },
  {
   "title": "Efficiency by ${operator}",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 11, "x": 13, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "rawSql": "\nSELECT \ndevice, sum(actual_qty)/sum(target_qty)::float * 100 as efficiency\nFROM  job_details\nWHERE '['$__timeFrom()', '$__timeTo()']'::tsrange @> shift\n  and operator = '$operator'\ngroup by machine"
    }
   ]
  },
  {
   "title": "Actual Strokes vs Actual Quantity by ${operator}",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 13, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select actual_qty actual_qty_produced, total_strokes strokes_taken\nFROM (\nselect operator, count(eventtime) total_strokes\nfrom job_details jd left join sensor s on jd.machine = s.machine and eventtime <@ shift\nwhere '['$__timeFrom()', '$__timeTo()']'::tsrange @> shift \ngroup by operator\n)s join (\n  select operator, sum(actual_qty) actual \n  from job_details \n  WHERE '['$__timeFrom()', '$__timeTo()']'::tsrange @> shift \n  GROUP BY operator\n) jd on s.operator = jd.operator\nwhere jd.operator = '${operator}'"
    }
   ]
  },
  {
   "title": "Idle strokes % by ${operator}",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 11, "x": 13, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "rawSql": "select (total_strokes-actual)/actual_qty::float * 100 efficiency\nFROM (\nselect operator, count(eventtime) total_strokes\nfrom job_details jd left join sensor s on jd.machine = s.machine and eventtime <@ shift\nwhere '['$__timeFrom()', '$__timeTo()']'::tsrange @> shift \ngroup by operator\n)s join (\n  select operator, sum(actual_qty) actual \n  from job_details \n  WHERE '['$__timeFrom()', '$__timeTo()']'::tsrange @> shift \n  GROUP BY operator\n) jd on s.operator = jd.operator\nwhere jd.operator = '${operator}'"
    }
   ]
  }
 ]
}